<?php

return [
    ['name' => 'Afghanistan', 'code' => '+93', 'iso' => 'af'],
    ['name' => 'Albania', 'code' => '+355', 'iso' => 'al'],
    ['name' => 'Algeria', 'code' => '+213', 'iso' => 'dz'],
    ['name' => 'Argentina', 'code' => '+54', 'iso' => 'ar'],
    ['name' => 'Australia', 'code' => '+61', 'iso' => 'au'],
    ['name' => 'Austria', 'code' => '+43', 'iso' => 'at'],
    ['name' => 'Belgium', 'code' => '+32', 'iso' => 'be'],
    ['name' => 'Brazil', 'code' => '+55', 'iso' => 'br'],
    ['name' => 'Canada', 'code' => '+1', 'iso' => 'ca'],
    ['name' => 'China', 'code' => '+86', 'iso' => 'cn'],
    ['name' => 'Egypt', 'code' => '+20', 'iso' => 'eg'],
    ['name' => 'France', 'code' => '+33', 'iso' => 'fr'],
    ['name' => 'Germany', 'code' => '+49', 'iso' => 'de'],
    ['name' => 'Ghana', 'code' => '+233', 'iso' => 'gh'],
    ['name' => 'India', 'code' => '+91', 'iso' => 'in'],
    ['name' => 'Italy', 'code' => '+39', 'iso' => 'it'],
    ['name' => 'Kenya', 'code' => '+254', 'iso' => 'ke'],
    ['name' => 'Netherlands', 'code' => '+31', 'iso' => 'nl'],
    ['name' => 'Nigeria', 'code' => '+234', 'iso' => 'ng'],
    ['name' => 'Norway', 'code' => '+47', 'iso' => 'no'],
    ['name' => 'South Africa', 'code' => '+27', 'iso' => 'za'],
    ['name' => 'Spain', 'code' => '+34', 'iso' => 'es'],
    ['name' => 'Sweden', 'code' => '+46', 'iso' => 'se'],
    ['name' => 'Switzerland', 'code' => '+41', 'iso' => 'ch'],
    ['name' => 'United Kingdom', 'code' => '+44', 'iso' => 'gb'],
    ['name' => 'United States', 'code' => '+1', 'iso' => 'us'],
];
